### ISSUE TITLE
Jquery 2.1.3 & Bootstrap 3.3.1

### ISSUE THREAD

**Issue by Lesac76** [dwmkerr/angular-modal-service#44]
Seem not to be compatible:
Console error: modal is not a function

**Comment by dwmkerr** [comment]
I'll check it now

**Comment by dwmkerr** [comment]
@Lesac76 can you try now with v0.6.2?

**Comment by Lesac76** [comment]
I had to deactivate the following line in the Controller where the modal is called:
//modal.element.modal();

And in the template I had to delete the top <div>


Then it works in the old version 0.6 and in the newest 0.6.3 in all current browsers (chrome, firefox, ie, safari) but without the nice dark background and fade in.

**Comment by dwmkerr** [comment]
Something is definitely wrong then, I've checked out the code to a clean location and it all works fine. Are you using the samples app? If so, make sure to use `gulp` not `grunt` to run it. Except for that it should work fine, backdrop included. And you'll need to use `modal.element.modal` to show the modal. What is your template looking like and what line did you delete?

**Comment by Lesac76** [comment]
https://github.com/dwmkerr/angular-modal-service/issues/14

You suggested on one of the older issues to extra include bootstrap modal. I tried that and it solved my problem. Seems like gulp wasn't including bootstrap js files.
